### ISSUE TITLE
Comment out code with "#if 0"

### ISSUE THREAD

**Issue by theta682** [lefticus/cppbestpractices#14]
Instead of commenting out the code with /* */ you can use:

```
#if 0
void function_f(int param)
{
  (void)param;
}
#endif
```

In this case you can nest such commented out parts. Moreover, syntax highlighting still work in some IDEs.

**Comment by lefticus** [comment]
That's true, but most things I've read lately suggest that we should never comment out code - once it's determined the code is not necessary, it should be removed,

So I'm not sure where this note should be made inside of a 'best practices' document.

**Comment by rob100** [comment]
Interesting, I did not knew this method to comment code out.
But I agree with lefticus: You should comment out code only temporary and before you commit a file to your version control system this should be removed. If you still need the old code you can lookup it in the version control system. Large blocks of old code can considerably decrease the readability of the source code.

**Comment by sbowman-mitre** [comment]
I have to admit that I really dislike this particular comment syntax and would consider it bad practice if I ran across it (like @rob100 , I've not encountered it before). It actually makes the code less readable because the two comment characters that implement the comment are small and do not visibly apply to each commented-out line of source. And, if an IDE still syntax highlights the lines between the # marks, that's even worse for readability. (That would be a bug in the IDE development IMHO. And IDE should help us read code as it would be executed, not obfuscate what is being compiled.) I recommend not including this comment syntax as a recommended practice.

**Comment by lefticus** [comment]
Ok, based on comments from @sbowman-mitre  and @rob100 I'm closing this.
